### ISSUE TITLE
Missing cookies causing session error

### ISSUE THREAD

**Issue by matmatt89** [MatteoCampinoti94/FALocalRepo#1]
Hello,
I have recently come across this program, but have not been able to run it. I've logged into Furaffinty (using the beta theme and without any ad blockers), exported my cookies into a json file (properly named) and placed it in the same directory as the executable file. When I run the program and try to download files it fails at the third check. After examining the cookie file, it seems to be missing the cookies named "n" and "s". I am unable to find which setting in my FA account or which third party cookie provides these. Any suggestions?

**Comment by MatteoCampinoti94** [comment]
What browser did you get the cookies from?

**Comment by MatteoCampinoti94** [comment]
Have you enabled the secure mode in FA's settings?

**Comment by MatteoCampinoti94** [comment]
'Account Settings' -> 'Account Security Level' -> 'Full Security Mode'

**Comment by MatteoCampinoti94** [comment]
The s cookie is a simple boolean it seems, it's set to 0 in my cookies.
The n cookie on the other hand is an epoch time, 1506534885 in my case (2017/09/27 17:54:45) and I think it's the time that particular session was created.

**Comment by MatteoCampinoti94** [comment]
I'll add a function to analyze the cookie file and help with errors like yours

**Comment by matmatt89** [comment]
Thank you for replying. I've enabled 'Full Security Mode' on FA but to no change; so I checked my browser. I had been using Firefox Quantum 60. After some experimentation, I rolled back to Firefox 56, exported the cookies and it seems to have worked. I know that Quantum has caused problems with extensions but I'm unaware how it caused this issue.

**Comment by MatteoCampinoti94** [comment]
You're welcome.
Happy to see it works now :)
No idea why that wuld be a problem, maybe version 60 stores cookies in a different format? If you need to create a new session try installing a different browser (Chrome/Chromium would be best as they store cookies in json format already soit makes it easier to export them) and use it only to login and export the cookies before uninstalling it and deleting all its local files.

**Comment by matmatt89** [comment]
Will do. Thank you for your help.

**Comment by MatteoCampinoti94** [comment]
You're welcome 🙂

**Comment by MatteoCampinoti94** [comment]
Added a function that checks the cookies file for errors if the program fails to create a session, hope it will help :)
